<h5>LOGIN.phtml</h5>

<h3> veuillez vous inscrire SVP</h3>
<br>
<form method="post" action="" enctype="multipart/form-data">
    <div>
        <input type="text" name="LoginID" placeholder=" Identifiant" />
    </div>
        <p> Tapez votre identifiant </p>


    <div>
        <input type="text" name="Pswd_1" placeholder=" Password"/>
    </div>
        <p> Tapez votre password </p>


    <div>
        <input type="text" name="Pswd_2" placeholder=" Password"/>
    </div>
        <p> Retapez votre password </p>

    <div>
        <input type="submit" value="ENVOYER" class="submitButton"/>
    </div>
    <br>
</form>

<?php
//    require('apps/traitement_register.php');
?>
<br>