<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" type="text/css" href="public/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="public/css/layer.css">
        <link href="https://fonts.googleapis.com/css?family=Comfortaa" rel="stylesheet">

        <title>Session PHP</title>
    </head>

    <body>

<?php
require('apps/header.php');
require('apps/content.php');
require('apps/footer.php');
?>

        <script src="public/js/jquery-3.1.0.min.js"></script>
        <script src="public/js/bootstrap.min.js"></script>
    </body>
</html>